// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/enterprise": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/api/generate-render": {
    params: {};
  };
  "/api/projects/save": {
    params: {};
  };
  "/api/projects/list": {
    params: {};
  };
  "/api/projects/get": {
    params: {};
  };
  "/visualizer/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/pricing" | "/community" | "/enterprise" | "/.well-known/appspecific/com.chrome.devtools.json" | "/api/generate-render" | "/api/projects/save" | "/api/projects/list" | "/api/projects/get" | "/visualizer/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "./routes/community.tsx": {
    id: "routes/community";
    page: "/community";
  };
  "./routes/enterprise.tsx": {
    id: "routes/enterprise";
    page: "/enterprise";
  };
  "./routes/chrome-devtools-probe.ts": {
    id: "routes/chrome-devtools-probe";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "./routes/api.generate-render.ts": {
    id: "routes/api.generate-render";
    page: "/api/generate-render";
  };
  "./routes/api.projects.save.ts": {
    id: "routes/api.projects.save";
    page: "/api/projects/save";
  };
  "./routes/api.projects.list.ts": {
    id: "routes/api.projects.list";
    page: "/api/projects/list";
  };
  "./routes/api.projects.get.ts": {
    id: "routes/api.projects.get";
    page: "/api/projects/get";
  };
  "./routes/visualizer.$id.tsx": {
    id: "routes/visualizer.$id";
    page: "/visualizer/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/pricing": typeof import("./app/./routes/pricing.tsx");
  "routes/community": typeof import("./app/./routes/community.tsx");
  "routes/enterprise": typeof import("./app/./routes/enterprise.tsx");
  "routes/chrome-devtools-probe": typeof import("./app/./routes/chrome-devtools-probe.ts");
  "routes/api.generate-render": typeof import("./app/./routes/api.generate-render.ts");
  "routes/api.projects.save": typeof import("./app/./routes/api.projects.save.ts");
  "routes/api.projects.list": typeof import("./app/./routes/api.projects.list.ts");
  "routes/api.projects.get": typeof import("./app/./routes/api.projects.get.ts");
  "routes/visualizer.$id": typeof import("./app/./routes/visualizer.$id.tsx");
};